development:
  adapter: mysql
  database: sportscar_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: sportscar_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: sportscar_production
  username: root
  password: 
  host: localhost
