require 'creditcard'
require 'fastercsv'

# Exit if the user didn't pass at least one argument.

(puts "#{$0} - a batch creditcard validator\nusage: #{$0} csv_file record_number"; exit) unless ARGV.length>0

filename      =  ARGV[0]
option_number  =  ARGV[1].to_i - 1

# Use FasterCSV to read the CSV from the file. 
# Chapter 15 covers FasterCSV in detail.

lines=FasterCSV.read(filename) 

# At times, CSV files may have blank lines - 
# particularly if they are generated by hand.
# The following call deletes all of the blank lines.

lines.delete_if do |line|
    line == []
end

lines.each do |line|
  # Here we insert a new field at user-specified location - 
  # it indicates whether the card is valid or not.
  line.insert(option_number+1, (line[option_number].creditcard? ? 'valid' : 'invalid'))
end

# Finally, we write out the completed CSV file to the screen.

lines.each do |line|
  puts line.to_csv 
end

